app/db/models/room.py
from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Boolean

from app.db import Base


class Room(Base):
    __tablename__ = "rooms"

    id: Mapped[int] = mapped_column(primary_key=True)
    number: Mapped[int] = mapped_column(unique=True)
    name: Mapped[Optional[str]] = mapped_column((String(50)), nullable=True)
    img_url: Mapped[Optional[str]] = mapped_column(String(), nullable=True)
    img_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    img_name_orig: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    is_reserved: Mapped[bool] = mapped_column(Boolean(), default=False)

    def __str__(self):
        return f"Номер кімнати № {self.number}: {self.name}"

app/__init__.py
from flask import Flask

from app.db.base import create_db
from app.routes.room import room_blueprint


app = Flask(__name__)
app.register_blueprint(room_blueprint)


def main():
    create_db()
    app.run(debug=True, port=80)

app/db/__init__.py
from app.db.base import Base, Session
from app.db.models.room import Room

app/routes/room.py
from uuid import uuid4
import random

from flask import Blueprint, render_template, request, redirect, url_for, flash

from app.db import Session, Room


room_blueprint = Blueprint("rooms", __name__)


@room_blueprint.get("/")
def index():
    with Session() as session:
        rooms = session.query(Room).where(Room.is_reserved == False).all()
        random.shuffle(rooms)
        return render_template("index.html", rooms=rooms)


@room_blueprint.route("/add_room/", methods=["POST", "GET"])
def add_room():
    if request.method == "POST":
        with Session() as session:
            number = request.form.get("number")
            name = request.form.get("name")
            img_name_orig = None
            img_name = None
            img_url = "/static/img/default.jpg"

            photo = request.files.get("photo")
            if photo and photo.filename:
                img_name_orig = photo.filename
                img_name = uuid4().hex
                img_url = f"/static/img/{img_name}." + img_name_orig.split(".")[-1]
                photo.save("app" + img_url)

            room = Room(
                number=number,
                name=name,
                img_url=img_url,
                img_name=img_name,
                img_name_orig=img_name_orig
            )
            session.add(room)
            session.commit()
            return redirect(url_for("rooms.index"))

    return render_template("add_room.html")


@room_blueprint.get("/reserve/<int:id>")
def reserve(id):
    with Session() as session:
        room = session.query(Room).where(Room.id == id).first()
        room.is_reserved = True
        session.commit()
        return render_template("reserved.html", room=room)


@room_blueprint.get("/manage-rooms/")
def manage_rooms():
    with Session() as session:
        rooms = session.query(Room).all()
        return render_template("manage_rooms.html", rooms=rooms)


@room_blueprint.get("/delete/<int:id>")
def delete_room(id):
    with Session() as session:
        room = session.query(Room).where(Room.id == id).first()
        session.delete(room)
        session.commit()
        return redirect(url_for("rooms.manage_rooms"))


@room_blueprint.route("/edit-room/<int:id>", methods=["GET", "POST"])
def edit_room(id):
    with Session() as session:
        room = session.query(Room).where(Room.id == id).first()
        if request.method == "POST":
            room.number = request.form.get("number")
            room.name = request.form.get("name")
            room.is_reserved = True if request.form.get("is_reserved") else False

            photo = request.files.get("photo")
            if photo and photo.filename:
                room.img_name_orig = photo.filename
                room.img_name = uuid4().hex
                room.img_url = f"/static/img/{room.img_name}." + room.img_name_orig.split(".")[-1]
                photo.save("app" + room.img_url)

            session.commit()
            return redirect(url_for("rooms.manage_rooms"))

        return render_template("edit_room.html", room=room)

app/templates/add_room.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">

        <form action="{{ url_for('rooms.add_room') }}" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Номер кімнати</label>
                <input type="number" class="form-control" name="number">
            </div>
            <div class="mb-3">
                <label class="form-label">Назва кімнати</label>
                <input type="text" class="form-control" name="name">
            </div>
            <div class="mb-3">
                <label class="form-label">Виберіть фото кімнати</label>
                <input type="file" accept="image/*" class="form-control" name="photo">
            </div>
            <button type="submit" class="btn btn-primary">Додати</button>
        </form>

    </div>
  </div>
</div>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} Головна сторінка {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "navigation.html" %}
    <br><br>
    {% block content %}
    {% endblock content %}
</body>
</html>

app/templates/edit_room.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">

        <form action="{{ url_for('rooms.edit_room', id=room.id) }}" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Номер кімнати</label>
                <input type="number" class="form-control" name="number" value="{{ request.form.get('number') or room.number }}">
            </div>
            <div class="mb-3">
                <label class="form-label">Назва кімнати</label>
                <input type="text" class="form-control" name="name" value="{{ request.form.get('name') or room.name }}">
            </div>
            <div class="mb-3">
                <img src="{{ room.img_url }}" width="100px">
                <label class="form-label">Виберіть фото кімнати для заміни</label>
                <input type="file" accept="image/*" class="form-control" name="photo">
            </div>
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" name="is_reserved" role="switch" id="flexSwitchCheckChecked" {% if room.is_reserved %} checked {% endif %}>
                <label class="form-check-label" for="flexSwitchCheckChecked">Зарезервовано</label>
            </div>
            <button type="submit" class="btn btn-primary">Змінити</button>
        </form>

    </div>
  </div>
</div>
{% endblock content %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">

<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-inner">
    {% for room in rooms %}
      {% if loop.index == 1 %}
        <div class="carousel-item active">
      {% else %}
        <div class="carousel-item">
      {% endif %}
          <img src="{{ room.img_url }}" class="d-block w-10" width="500px">
          <div class="carousel-caption d-none d-md-block">
              <h5 style="color:rgb(201, 201, 219)">№ {{ room.number }}</h5>
              <p style="color:blueviolet">{{ room.name }}</p>
              <a class="btn btn-primary" href="{{ url_for('rooms.reserve', id=room.id) }}">Забронювати</a>
          </div>
        </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>
</div>
</div>

{% endblock content %}

app/templates/manage_rooms.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row align-items-center">
    {% for room in rooms %}
    <div class="col">
      <div class="card text-center" style="width: 18rem;">
        <img src="{{ room.img_url }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ room }}</h5>
          {% if room.is_reserved %}
            <button class="btn btn-success">Зарезервовано</button>
          {% endif %}
          <a href="{{ url_for('rooms.delete_room', id=room.id)}}" class="btn btn-danger">Видалити кімнату</a>
          <a href="{{ url_for('rooms.edit_room', id=room.id)}}" class="btn btn-primary">Редагувати кімнату</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

app/templates/navigation.html
<nav>
    <a class="btn btn-success" href="{{ url_for('rooms.index') }}">Головна сторінка</a>
    <a class="btn btn-success" href="{{ url_for('rooms.manage_rooms') }}">Редагування кімнат</a>
    <a class="btn btn-success" href="{{ url_for('rooms.add_room') }}">Додати нову кімнату</a>
</nav>

app/templates/reserved.html
{% extends "base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
  <img src="{{ room.img_url }}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">Вітаю! Ви забронювали чудовий номер.</h5>
    <p class="card-text">{{ room }}</p>
    <a href="{{ url_for('rooms.index') }}" class="btn btn-primary">Перейти на головну сторінку</a>
  </div>
</div>
{% endblock content %}